version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - npm install
  build:
    commands:
      - npm run build:prod
artifacts:
  files:
    - dist*/**
  discard-paths: yes